<?php
/**
 * EliteGuard Security & Crypto Component
 * Neutral security helper for Elite Developers PHP applications.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

if (!defined('ELITE_ACCESS_KEY')) {
    exit('Direct access denied.');
}

class EliteSecurity {
    
    /**
     * Normalize domain string for consistent validation.
     * e.g. "https://WWW.Example.com/subpath/" -> "example.com"
     */
    public static function normalizeDomain(string $url): string {
        // Strip scheme
        $domain = preg_replace('#^https?://#i', '', $url);
        // Strip path and port
        $domain = explode('/', $domain)[0];
        $domain = explode(':', $domain)[0];
        // Strip www. prefix and convert to lowercase
        $domain = strtolower($domain);
        if (str_starts_with($domain, 'www.')) {
            $domain = substr($domain, 4);
        }
        return trim($domain);
    }

    /**
     * Collect anonymous server diagnostic payload
     */
    public static function getEnvironmentPayload(): array {
        $host = $_SERVER['HTTP_HOST'] ?? $_SERVER['SERVER_NAME'] ?? 'localhost';
        return [
            'access_key'      => ELITE_ACCESS_KEY,
            'domain'          => self::normalizeDomain($host),
            'ip_address'      => $_SERVER['SERVER_ADDR'] ?? $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
            'php_version'     => PHP_VERSION,
            'server_software' => $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown',
            'script_version'  => defined('ELITE_APP_VERSION') ? ELITE_APP_VERSION : '1.0.0',
            'timestamp'       => time(),
        ];
    }

    /**
     * Verify HMAC SHA256 signature from EliteGuard Server response
     */
    public static function verifySignature(array $response, string $secret): bool {
        if (!isset($response['signature'], $response['timestamp'], $response['data'])) {
            return false;
        }

        // Prevent replay attacks beyond 5 minutes window
        if (abs(time() - (int)$response['timestamp']) > 300) {
            return false;
        }

        $expectedSig = hash_hmac('sha256', json_encode($response['data']) . '.' . $response['timestamp'], $secret);
        return hash_equals($expectedSig, $response['signature']);
    }

    /**
     * Verify remote command signature payload
     */
    public static function verifyCommandSignature(array $command, string $secret): bool {
        if (!isset($command['id'], $command['command_type'], $command['installation_id'], $command['timestamp'], $command['signature'])) {
            return false;
        }

        // Replay protection: prevent command execution older than 5 minutes
        if (abs(time() - (int)$command['timestamp']) > 300) {
            return false;
        }

        $payloadStr = json_encode($command['payload'] ?? []);
        $toSign = $command['id'] . '.' . $command['command_type'] . '.' . $command['installation_id'] . '.' . $command['timestamp'] . '.' . $payloadStr;
        $expectedSig = hash_hmac('sha256', $toSign, $secret);

        return hash_equals($expectedSig, $command['signature']);
    }
}
